#!/bin/sh

# check that required input are properly set
[ -z $HOSTNAME ] && echo You need to set environment variable HOSTNAME && exit
[ -z $IDENTIFIER ] && echo You need to set environment variable IDENTIFIER && exit
[ -z $PASSWORD ] && echo You need to set environment variable PASSWORD && exit

# retrieve last known (cached) address and current public address
CACHED_IP_ADDRESS=$(cat /dynhost/cached_address 2>/dev/null)
PUBLIC_IP_ADDRESS=$(dig @resolver4.opendns.com myip.opendns.com +short)

# compare current address to cached one to avoid useless updates
if [ "$CACHED_IP_ADDRESS" != "$PUBLIC_IP_ADDRESS" ]
then
    echo "$(date +"%Y-%m-%d/%T") - INFO - Cached address changed from '$CACHED_IP_ADDRESS' to '$PUBLIC_IP_ADDRESS'"
    # update DynHost record using OVH API
    ovh_response=$(curl -sS "http://www.ovh.com/nic/update?system=dyndns&hostname=${HOSTNAME}&myip=${PUBLIC_IP_ADDRESS}" \
        -H "Authorization: Basic $(echo -n $IDENTIFIER:$PASSWORD | base64)")
    echo "$(date +"%Y-%m-%d/%T") - INFO - OVH response: ${ovh_response}"
    # cache address for comparison, to avoid useless updates
    echo $PUBLIC_IP_ADDRESS > cached_address
else
    echo "$(date +"%Y-%m-%d/%T") - DEBUG  - No changes detected"
fi
